PoET 2 skeletal implementation
askmish/sawtooth-core pull request #2
Opened 2018-06-15 10:24 UTC by rranjan3

Building cargo project under consensus directory.
Adding main,engine,driver,service implementations.
Integrating with build & test systems. Adding
docker support files for running tests.

Signed-off-by: Rajeev Ranjan <rajeev2.ranjan@intel.com>

2018-06-18 05:01 UTC, askmish requested changes

2018-06-18 05:01 UTC, askmish commented on consensus/poet2/core/src/engine.rs
> +                        Update::PeerMessage(message, sender_id) => match DevmodeMessage::from_str(
Remove dependencies on DevmodeMessage

2018-06-18 05:02 UTC, askmish commented on consensus/poet2/core/src/engine.rs
> +                        Update::PeerMessage(message, sender_id) => match DevmodeMessage::from_str(
Also rebase into one single meaningful commit.

2018-06-18 12:50 UTC, rranjan3 commented
Have merged the commits. But yet to do away with the DevmodeMessage dependency.

2018-06-22 05:32 UTC, askmish approved these changes

2018-06-22 05:32 UTC, merged